### ISSUE TITLE
option '-lmtmp' not recognized

### ISSUE THREAD

**Issue by thilko** [FIWARE/helm-charts#11]
It seems that the last change broke the helm chart for `orion`. Error message is

```
option '-lmtmp' not recognized
```

Change was introduced with this commit: https://github.com/FIWARE/helm-charts/commit/698869e6fb5199ebb37b04d4e4010dde3912a18c

**Comment by kzangeli** [comment]
That option is a hidden option I implemented for Orion-LD ... Are you trying to start Orion with that option?  If so, not gonna work. It's an Orion-LD option only

**Comment by thilko** [comment]
Yes, it´s about starting an orion.
